#!/bin/sh

ldir="../../../libvncserver"

fail=""
if [ ! -f "./tight.c" ]; then
	fail=1
fi
if [ ! -f "./turbojpeg.h" ]; then
	fail=1
fi
if [ ! -f "./convert" ]; then
	fail=1
fi
if [ ! -f "$ldir/tight.c" ]; then
	ls -l "$ldir/tight.c"
	fail=1
fi
if [ ! -f "$ldir/rfbserver.c" ]; then
	ls -l "$ldir/rfbserver.c"
	fail=1
fi
if [ "X$fail" = "X1" ]; then
	echo "Must be run from inside the directory containing 'apply_turbovnc'"
	exit 1
fi

set -x
if [ ! -f "$ldir/tight.c.ORIG" ]; then
	cp -p "$ldir/tight.c" "$ldir/tight.c.ORIG"
fi
if [ ! -f "$ldir/rfbserver.c.ORIG" ]; then
	cp -p "$ldir/rfbserver.c" "$ldir/rfbserver.c.ORIG"
fi

perl ./convert ./tight.c > "$ldir/tight.c"
perl ./convert_rfbserver $ldir/rfbserver.c.ORIG > "$ldir/rfbserver.c"
cp -p ./turbojpeg.h "$ldir"
ls -l $ldir/tight.c* $ldir/rfbserver.c* $ldir/turbojpeg.h
