#!/bin/sh
#
# This script has been (or is hereby) released into the public domain by
# its author, Karl J. Runge <runge@karlrunge.com>. This applies worldwide.
# 
# In case this is not legally possible: Karl J. Runge grants anyone the
# right to use this work for any purpose, without any conditions, unless
# such conditions are required by law.

ldir="../../../libvncserver"

if [ ! -f "$ldir/tight.c.ORIG" ]; then
	ls -l "$ldir/tight.c.ORIG"
	exit 1
fi
if [ ! -f "$ldir/rfbserver.c.ORIG" ]; then
	ls -l "$ldir/rfbserver.c.ORIG"
	exit 1
fi

set -xv
rm -f "$ldir/tight.c" "$ldir/turbojpeg.h"
mv "$ldir/tight.c.ORIG" "$ldir/tight.c"
mv "$ldir/rfbserver.c.ORIG" "$ldir/rfbserver.c"
ls -l $ldir/tight.c* $ldir/rfbserver.c*
